export const jobsConstants = {
    JOB_LIST_REQUEST: 'JOB_LIST_REQUEST',
    JOB_LIST: 'JOB_LIST',
    JOB_SELECT_REQUEST: 'JOB_SELECT_REQUEST',
    JOB_SELECT: 'JOB_SELECT',
    APPLY: 'APPLY',
    APPLY_REQUEST: 'APPLY_REQUEST',
    CANCEL_APPLICATION: 'CANCEL_APPLICATION',
    CANCEL_APPLICATION_REQUEST: 'CANCEL_APPLICATION_REQUEST',
};
